// Shared degree lists used by the signup and profile pages.
// Keep them in one place so both pages save degrees in the same format,
// e.g. "Biological and Agricultural Engineering (B.S.)".

export const TAMU_DEGREES = [
  // Agricultural degrees (most common, kept at the top)
  "Biological and Agricultural Engineering (B.S.)",
  "Biological and Agricultural Engineering (M.S.)",
  "Biological and Agricultural Engineering (M.Eng.)",
  "Biological and Agricultural Engineering (Ph.D.)",
  "Agricultural Systems Management (B.S.)",
  "Agricultural Systems Management (M.S.)",
  "Agricultural Communications and Journalism (B.S.)",
  "Agricultural Economics (B.S.)",
  "Agricultural Education (B.S.)",
  "Agricultural Leadership and Development (B.S.)",

  // Agriculture & Life Sciences
  "Agribusiness (B.S.)",
  "Animal Science (B.S.)",
  "Biochemistry (B.S.)",
  "Bioenvironmental Sciences (B.S.)",
  "Ecology and Conservation Biology (B.S.)",
  "Entomology (B.S.)",
  "Environmental Studies (B.S.)",
  "Financial Planning (B.S.)",
  "Food Science and Technology (B.S.)",
  "Forensic and Investigative Sciences (B.S.)",
  "Genetics (B.S.)",
  "Horticulture (B.A.)",
  "Horticulture (B.S.)",
  "Hospitality, Hotel Management and Tourism (B.S.)",
  "Nutrition (B.S.)",
  "Plant and Environmental Soil Science (B.S.)",
  "Poultry Science (B.S.)",
  "Rangeland, Wildlife and Fisheries Management (B.S.)",
  "Turfgrass Science (B.S.)",

  // Architecture
  "Architecture (B.S.)",
  "Construction Science (B.S.)",
  "Landscape Architecture (B.L.A.)",
  "Urban and Regional Planning (B.S.)",

  // Arts & Sciences
  "Anthropology (B.A.)",
  "Anthropology (B.S.)",
  "Applied Mathematics (B.S.)",
  "Behavioral and Cognitive Neuroscience (B.S.)",
  "Bioinformatics (B.S.)",
  "Biology (B.A.)",
  "Biology (B.S.)",
  "Chemistry (B.A.)",
  "Chemistry (B.S.)",
  "Classics (B.A.)",
  "Communication (B.A.)",
  "Communication (B.S.)",
  "Economics (B.A.)",
  "Economics (B.S.)",
  "English (B.A.)",
  "Environmental and Sustainability Studies (B.S.)",
  "Environmental Systems Science (B.S.)",
  "Geographic Information Science and Technology (B.S.)",
  "Geography (B.S.)",
  "Geology (B.A.)",
  "Geology (B.S.)",
  "Geophysics (B.S.)",
  "Global Studies (B.A.)",
  "History (B.A.)",
  "History (B.S.)",
  "Journalism (B.A.)",
  "Journalism (B.S.)",
  "Mathematics (B.A.)",
  "Mathematics (B.S.)",
  "Meteorology (B.S.)",
  "Microbiology (B.S.)",
  "Modern Languages (B.A.)",
  "Molecular and Cell Biology (B.S.)",
  "Neurobiology (B.S.)",
  "Ocean Studies (B.A.)",
  "Oceanography (B.S.)",
  "Philosophy (B.A.)",
  "Physics (B.A.)",
  "Physics (B.S.)",
  "Psychology (B.A.)",
  "Psychology (B.S.)",
  "Society, Ethics, and Law (B.A.)",
  "Sociology (B.A.)",
  "Sociology (B.S.)",
  "Spanish (B.A.)",
  "Statistics (B.S.)",
  "Telecommunication Media Studies (B.A.)",
  "Telecommunication Media Studies (B.S.)",
  "Zoology (B.S.)",

  // Business
  "Accounting (B.B.A.)",
  "Business (B.S.)",
  "Business Honors (B.B.A.)",
  "Finance (B.B.A.)",
  "Management (B.B.A.)",
  "Management Information Systems (B.B.A.)",
  "Marketing (B.B.A.)",
  "Supply Chain Management (B.B.A.)",

  // Engineering
  "Aerospace Engineering (B.S.)",
  "Architectural Engineering (B.S.)",
  "Biomedical Engineering (B.S.)",
  "Chemical Engineering (B.S.)",
  "Civil Engineering (B.S.)",
  "Computer Engineering (B.S.)",
  "Computer Science (B.A.)",
  "Computer Science (B.S.)",
  "Data Engineering (B.S.)",
  "Electrical Engineering (B.S.)",
  "Electronic Systems Engineering Technology (B.S.)",
  "Environmental Engineering (B.S.)",
  "Industrial Distribution (B.S.)",
  "Industrial Engineering (B.S.)",
  "Interdisciplinary Engineering (B.S.)",
  "Manufacturing and Mechanical Engineering Technology (B.S.)",
  "Materials Science and Engineering (B.S.)",
  "Mechanical Engineering (B.S.)",
  "Multidisciplinary Engineering Technology (B.S.)",
  "Nuclear Engineering (B.S.)",
  "Ocean Engineering (B.S.)",
  "Petroleum Engineering (B.S.)",
  "Space Engineering (B.S.)",

  // Government & Public Service
  "International Affairs (B.A.)",
  "Political Science (B.A.)",
  "Political Science (B.S.)",
  "Public Service and Administration (B.A.)",
  "Public Service and Administration (B.S.)",

  // Public Health
  "Public Health (B.S.)",

  "Other",
];

// Degree types for the "Other" option
export const DEGREE_TYPES = [
  "B.S.",
  "B.A.",
  "B.B.A.",
  "B.F.A.",
  "B.L.A.",
  "B.S.N.",
  "M.S.",
  "M.A.",
  "M.Eng.",
  "M.B.A.",
  "M.P.A.",
  "M.Ed.",
  "Ph.D.",
  "Ed.D.",
  "J.D.",
  "M.D.",
  "D.V.M.",
];
